#!/bin/bash
#Ejercicio 4 TP 1 - Sistemas Operativos 

#Funciones de Script

#Funciones AWK
function validarContenidoArchivo() {
	awk -F ':' ' 
	{
	error=0;

	#Valida cantidad de campos por registro sea 2 o registro vacio
	if (NF != 2 && NF != 0) { error=1; }
	
	#Valida unicos nombres de campos permitidos 
	if ( NF==2  && $1 != "Cliente" && $1 != "Fecha compra" && $1 != "Vencimiento"  && $1 != "Estado") { error=1; }
	}


	END { print error }' $1  
}

#funcion que valida campos para archivo de entrada que pueden contener fecha
function validarFecha() {
	awk -F ':' ' BEGIN {error=0;}
	#Valida formato de fecha de entrada mm/dd/aaaa
	($1 == "Fecha compra" || $1 == "Vencimiento") && $2 !~ /(0[1-9]|1[012])\/(0[1-9]|[12][0-9]|3[01])\/(19|20)[0-9][0-9]/ { error=1; }
	END { print error }' $1
}

#Funciones de Validaciones
function validarParametros() {
#Chequea si el primer parametro es llamada a ayuda
if [ "$1" = "-?" ]; then
	msg="Se invoco ayuda de script";
	return 1;
#chequea cantidad de parametros pasados
elif [ "$#" -ne 2 ]; then
	msg="ERROR: Cantidad de Parametros incorrectos"
	return 1;	
#chequea que parametro 1 sea archivo	
elif  [ ! -f "$1" ]; then
	msg="ERROR: Parametro pasado $1 no es un archivo"
	return 1;
#chequea que no este vacio el archivo
elif [ ! -s "$1" ]; then
	msg="ERROR: $1 esta vacio o no existe ."
	return 1;
#chequea que parametro 2 sea directorio
elif [ ! -d "$2" ]; then
	msg="ERROR: $2 no es un directorio"
	return 1;
fi
}

function usage() {
	echo "#########################################################"
	echo "# USO DEL SCRIPT:                                       #"
	echo "# Ejercicio4 param1 param2                              #"
	echo "# param1 > archivo a procesar                           #"
	echo "# param2 > directorio donde se guarda archivo resultado #"
	echo "#########################################################"
}

function validaciones() {
validarParametros $*
if [ "$?" -eq 1 ]; then
	echo "$msg"
	usage
	return 1;
fi
res=`validarContenidoArchivo $1`
res=`validarFecha $1`
if [ "$res" -eq 1 ]; then
	echo "Error en contenido de archivo de entrada, formato erroneo en campos o malformado"
	return 1;
fi

echo "No hubo errores"
return 0;

return fail;
}


#Parte principal de Script
validaciones $*
if [ $? -eq 1 ]; then
	exit 1
else
	echo "entrando al main"
fi





