#!/bin/bash

#Ejercicio 4 TP 1 - Sistemas Operativos
#Fecha de Creación: 21/08/2013

#INTEGRANTES DEL GRUPO
#Sergio Defusto
#Juan Marcos Bruno
#Sharon Denise Pesca Alba
#
#

#OBJETIVO
#Transformar un archivo de entrada con datos de clientes en un archivo de salida donde las fechas modifiquen su formato y se agreguen en caso de corresponder nuevos vencimientos con un agregado de 15 días sobre los vencimientos iniciales.

#SINTAXIS: ./clientes.sh [archivo_a_procesar] [ruta_de_archivo_salida]

####################-------------------------------##########################

 #Funciones de Script

#Funciones de Validaciones
function validarParametros() {
#Chequea si el primer parametro es llamada a ayuda
if [ "$1" = "-?" ]; then
	msg="Se invoco ayuda de script";
	return 1;
#chequea cantidad de parametros pasados
elif [ "$#" -ne 2 ]; then
	msg="ERROR: Cantidad de Parametros incorrectos"
	return 1;	
#chequea que parametro 1 sea archivo	
elif  [ ! -f "$1" ]; then
	msg="ERROR: Parametro pasado $1 no es un archivo"
	return 1;
#chequea que no este vacio el archivo
elif [ ! -s "$1" ]; then
	msg="ERROR: $1 esta vacio o no existe ."
	return 1;
#chequea que parametro 2 sea directorio
elif [ ! -d "$2" ]; then
	msg="ERROR: $2 no es un directorio"
	return 1;
fi
}

function usage() {
	echo "#########################################################"
	echo "# USO DEL SCRIPT:                                       #"
	echo "# Ejercicio4 param1 param2                              #"
	echo "# param1 > archivo a procesar                           #"
	echo "# param2 > directorio donde se guarda archivo resultado #"
	echo "#########################################################"
}


#FUNCION OUTPUT para probar registros en archivo salida
function output(){
	
	#archivo_tmp="/tmp/log_errores";	
	arch_salida="clientes.out";
	
	if test  -s $arch_salida; then
		clear		
		echo "resultado en archivo salida";
		cat $arch_salida;
		echo
		#mv "clientes.out" $2; hacer el move.
	fi
}

#Parte principal de Script
validarParametros $*

if [ "$?" -eq 1 ]; then
	echo "$msg"
	usage	
elif test -s $1; then

	#SE PROCESA EL ARCHIVO
	awk -f ej4.awk $1 > clientes.out
	output 

fi






